{% set name = "metomi-isodatetime" %}
{% set version = "1!3.1.0" %}
{% set python_min = "3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2ec15eb9c323d5debd0678f33af99bc9a91aa0b534ee5f65f3487aed518ebf2d

build:
  noarch: python
  number: 1
  entry_points:
    - isodatetime=metomi.isodatetime.main:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - pytest-runner
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - metomi.isodatetime
  commands:
    - isodatetime --help
    - test "$(isodatetime 2000 --offset -P1Y)" -eq 1999

about:
  home: https://github.com/metomi/isodatetime
  license: LGPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Python ISO 8601 date time parser and data model/manipulation utilities
  description: |
    Python ISO8601 (2004) full-specification parser and data
    model/manipulation utilities. Intended to be used in a similar
    way to Python's datetime module.
  doc_url: https://github.com/metomi/isodatetime
  dev_url: https://github.com/metomi/isodatetime

extra:
  recipe-maintainers:
    - MetRonnie
    - wxtim
    - oliver-sanders
