{% set name = "metomi-isodatetime" %}
{% set version = "1!3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2141e8aaa526ea7f7f1cb883e6c8ed83ffdab73269658d84d0624f63a6e1357e

build:
  noarch: python
  number: 0
  entry_points:
    - isodatetime=metomi.isodatetime.main:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - pytest-runner
    - python  >=3.7
  run:
    - python  >=3.7

test:
  imports:
    - metomi.isodatetime
  commands:
    - isodatetime --help

about:
  home: https://github.com/metomi/isodatetime
  license: LGPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: Python ISO 8601 date time parser and data model/manipulation utilities
  description: |
    Python ISO8601 (2004) full-specification parser and data
    model/manipulation utilities. Intended to be used in a similar
    way to Python's datetime module.
  doc_url: https://github.com/metomi/isodatetime
  dev_url: https://github.com/metomi/isodatetime

extra:
  recipe-maintainers:
    - kinow
    - wxtim
    - oliver-sanders
